version: '3.8'

name: librarymanager

services:

    postgres:
        image: postgres:alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: mydatabase 
        ports:
            - '5432:5432'

    backend:
        depends_on:
            - postgres
        restart: unless-stopped
        build:
            context: .
            dockerfile: apps/backend/Dockerfile
        ports:
            - '3000:3000'