version: '3.8'

name: librarymanager

services:

    postgres:
        image: postgres:alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: mydatabase 
        ports:
            - '5432:5432'